export const catalogImages = [
  "/images/catalog/_ (21).jpeg",
  "/images/catalog/_ (1).jpeg",
  "/images/catalog/_ (5).jpeg",
  "/images/catalog/_ (3).jpeg",
  "/images/catalog/_ (8).jpeg",
  "/images/catalog/_ (11).jpeg",
  "/images/catalog/_ (15).jpeg",
  "/images/catalog/_ (18).jpeg",
  "/images/catalog/_ (13).jpeg",
  "/images/catalog/_ (24).jpeg",
  "/images/catalog/_ (27).jpeg",
  "/images/catalog/_ (30).jpeg",
  "/images/catalog/_ (33).jpeg",
  "/images/catalog/_ (35).jpeg",
  "/images/catalog/_ (39).jpeg",
  "/images/catalog/_ (41).jpeg",
  "/images/catalog/_ (43).jpeg",
  "/images/catalog/_.jpeg",
  "/images/catalog/🕷.jpeg",
  "/images/catalog/2025_1_70_088.avif",
  "/images/catalog/Bleach 🖤 (1).jpeg",
  "/images/catalog/christian harper.jpeg",
  "/images/catalog/devour feculence.jpeg",
  "/images/catalog/eva.jpeg",
  "/images/catalog/Gladiator.jpeg",
  "/images/catalog/IMG_7899.JPG",
  "/images/catalog/IMG_7902.JPG",
  "/images/catalog/IMG_7905.JPG",
  "/images/catalog/Vagabond Magna Poster on Behance.jpeg",
  "/images/catalog/W CHROMAKOPIA.jpeg",
  "/images/catalog/The Lobster.jpeg",
  "/images/catalog/se7en.jpeg",
  "/images/catalog/pierre-chatel-innocenti-dWBoc5jWYhY-unsplash.jpg",
  "/images/catalog/Nah, I'd Win_ Wallpapers.jpeg",
  "/images/catalog/MANSOOR - A9BDB886-26DE-4E59-B2BC-666AF03F7252 – Savee.jpeg",
  "/images/catalog/Life looks great on film_ #bershkastyle #bershka.jpeg",
  "/images/catalog/large_FW_25_Lookbook_20_ccdbb358ea.jpg",
  "/images/catalog/jack-dixon-T0T-D_EJ1hE-unsplash.jpg",
  "/images/catalog/Interstellar _ Wallpaper.jpeg",
  "/images/catalog/IMG_7913.JPG",
  "/images/catalog/IMG_7909.JPG",
  "/images/catalog/IMG_7907.JPG",
  "/images/catalog/_ (9).jpeg",
  "/images/catalog/_ (6).jpeg",
  "/images/catalog/_ (17).jpeg",
  "/images/catalog/_ (19).jpeg",
  "/images/catalog/_ (22).jpeg",
  "/images/catalog/_ (25).jpeg",
  "/images/catalog/_ (28).jpeg",
  "/images/catalog/_ (31).jpeg",
  "/images/catalog/_ (38).jpeg",
  "/images/catalog/_ (36).jpeg",
  "/images/catalog/2025_1_70_064.avif",
  "/images/catalog/Artist Paints Over Gundam Action Figures To Make Them Look Like They’ve Stepped Straight Out Of An A.jpeg",
  "/images/catalog/Bleach 🖤.jpeg",
  "/images/catalog/chromakopia.jpeg",
  "/images/catalog/large_FW_25_Lookbook_52_d7fe6d03e8.jpg",
  "/images/catalog/Mahoraga Wallpaper.jpeg",
  "/images/catalog/MIL 1978  by Camper.jpeg",
  "/images/catalog/Older guys.jpeg",
  "/images/catalog/premium_photo-1664304582040-4f6c69c8380c.avif",
  "/images/catalog/valentin-salja-tOhkfHtINt8-unsplash.jpg",
  "/images/catalog/Tubro Granny.jpeg",
  "/images/catalog/sebastian-sammer-gIfmeidaaTc-unsplash.jpg",
  "/images/catalog/viktor-theo-BNQX9TKxu8Q-unsplash.jpg",
  "/images/catalog/My attempt on Interstellar (2014) minimalist poster [1920x2880].jpeg",
  "/images/catalog/IMG_7910.JPG",
  "/images/catalog/IMG_7904.JPG",
  "/images/catalog/grigorii-shcheglov-tbXwGRBzlUg-unsplash.jpg",
  "/images/catalog/FW25AG004_BoxingGloves_PineGrove_1_3200x.webp",
  "/images/catalog/dynamic-wang-pBXRbUHZC54-unsplash.jpg",
  "/images/catalog/＊_•̩̩͙✩•̩̩͙_˚　˚_•̩̩͙✩•̩̩͙_˚＊.jpeg",
  "/images/catalog/_ (26).jpeg",
  "/images/catalog/_ (10).jpeg",
  "/images/catalog/_ (12).jpeg",
  "/images/catalog/_ (2).jpeg",
  "/images/catalog/_ (4).jpeg",
  "/images/catalog/_ (7).jpeg",
  "/images/catalog/_ (14).jpeg",
  "/images/catalog/_ (16).jpeg",
  "/images/catalog/_ (20).jpeg",
  "/images/catalog/_ (23).jpeg",
  "/images/catalog/_ (29).jpeg",
  "/images/catalog/_ (32).jpeg",
  "/images/catalog/_ (34).jpeg",
  "/images/catalog/Tokyo 351.jpeg",
  "/images/catalog/Tame Impala Currents wallpaper.jpeg",
  "/images/catalog/Sakamoto Days.jpeg",
  "/images/catalog/peter-thomas-lMN18_mBSYc-unsplash.jpg",
  "/images/catalog/LOEWE.jpeg",
  "/images/catalog/Jean barrel Anagram en denim Bleu - LOEWE.jpeg",
  "/images/catalog/large_FW_25_Lookbook_26_0dd46d49c7.jpg",
  "/images/catalog/Letter Embroidery Denim Stripe Button Pocket Wide Leg Barrel Jeans.jpeg",
  "/images/catalog/IMG_7911.JPG",
  "/images/catalog/IMG_7914.JPG",
  "/images/catalog/IMG_7915.JPG",
  "/images/catalog/Interstellar.jpeg",
  "/images/catalog/IMG_7906.JPG",
  "/images/catalog/IMG_7908.JPG",
  "/images/catalog/IMG_7903.JPG",
  "/images/catalog/IMG_7901.JPG",
  "/images/catalog/IMG_7900.JPG",
  "/images/catalog/IMG_7573.JPG",
  "/images/catalog/Gizem Akdag (@gizakdag) on X.jpeg",
  "/images/catalog/eduardo-gutierrez-GCy97cuhmf0-unsplash.jpg",
  "/images/catalog/𝐂𝐎𝐖𝐁𝐎𝐘 𝐁𝐄𝐁𝐎𝐏.jpeg",
  "/images/catalog/charlesdeluvio-NbjjcaoymIo-unsplash.jpg",
  "/images/catalog/Apricot princess by Rex orange county album cover expanded.jpeg",
  "/images/catalog/_ (37).jpeg",
  "/images/catalog/_ (40).jpeg",
  "/images/catalog/_ (42).jpeg",
  "/images/catalog/_ (44).jpeg",
  "/images/catalog/#bmw #car #carposter #poster #graphicdesign.jpeg",
  "/images/catalog/2001 A Space Odyssey (1968).jpeg",
];
